name: DART Telegram Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # run every 5 minutes (UTC) for testing
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests pandas
      - name: Run bot
        env:
          DART_API_KEY: ${{ secrets.DART_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python dart_bot.py